on: pull_request
name: Debug
jobs:
  dump:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  status:
    name: Status
    runs-on: ubuntu-latest
    steps:
      - run: |
          export GITHUB_API_URL="https://api.github.com/repos/arnested/playground/statuses/${{ github.event.after }}"
          export STATE="success"
          export ARTIFACT_URL="https://arnested"
          export STATUS_DATA="{\"state\": \"${STATE}\", \"description\": \"Pull request status\", \"context\": \"pull request status\", \"target_url\": \"${ARTIFACT_URL}\"}"
          curl --fail --silent -X POST --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --url "$GITHUB_API_URL" --header "Content-Type: application/json" --data "$STATUS_DATA"
