name: Test VPN
on: [ push, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup-vpn-client-meraki
        uses: matcontardo/setup-vpn-client-meraki@1.5
        with:
          server: ${{ secrets.VPN_SERVER }}
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}
          psk: ${{ secrets.VPN_PSK }}
          network_route: ${{ secrets.VPN_NETWORK_ROUTE }}
          test_ip: ${{ secrets.VPN_SERVER }}

      - run: curl https://pr-1085.webtestbupl.dk
