name: Dump contexts
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Foo
        uses: arnested/playground-action@v1
      - run: |
          curl --fail --silent -X POST --user ":${{github.token}}" "https://api.github.com/repos/arnested/playground/statuses/${{ github.sha }}" --data "{\"state\": \"pending\", \"description\": \"foo bar\", \"context\": \"Visual regression test\"}"
      - run: |
          echo github.ref: ${{ github.ref }}
          echo github.event.repository.default_branch: ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}
          echo Default branch: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Shoutrrr ${{ github.event.repository.default_branch }}
        uses: containrrr/shoutrrr-action@v1
        with:
          url: hangouts://chat.googleapis.com/v1/spaces/AAAAyeSJ9u0/messages?key=${{ secrets.HANGOUTS_KEY }}
          message: Default branch is ${{ github.event.repository.default_branch }}.
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
