name: Go build
on: [ push, workflow_dispatch ]

env:
  VERSION: 1.24.2

permissions:
  security-events: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Fetch alerts using REST API to trigger bad token alert
        run: gh api /repos/${{ github.repository }}/dependabot/alerts
        env:
          GH_TOKEN: ${{ github.token }}
      - id: go-cache
        shell: bash
        run: |
          echo -e "GOCACHE=$(go env GOCACHE)\nGOMODCACHE=$(go env GOMODCACHE)" >> "${GITHUB_OUTPUT}"
      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.go-cache.outputs.GOCACHE }}
            ${{ steps.go-cache.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-${{ runner.arch }}-go${{ env.VERSION }}
      - run: go version
      - run: go env
      - name: Install go ${{ env.VERSION }}
        shell: bash
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          GOBIN=$(go env GOPATH)/bin
          export GOBIN

          go install "golang.org/dl/go${VERSION}@latest"
          "${GOBIN}/go${VERSION}" download

          ln -sf "${GOBIN}/go${VERSION}" "${GOBIN}/go"

          echo "${GOBIN}" >> "${GITHUB_PATH}"
      - run: go version
      - run: go env
      - run: go build
        working-directory: ./go
      - run: ./go
        working-directory: ./go
